[build-system]
requires = ["setuptools>=68", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "rbeval"
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "seaborn>=0.13.2"
]

[project.optional-dependencies]
eval = [
    "lm-eval[vllm]==0.4.3"
]

# Enables the usage of setuptools_scm
[tool.setuptools_scm]
