[build-system]
requires = ["setuptools>=68", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "rbeval"
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "pandas>=2.2.2",
    "matplotlib>=3.9.1",
    "huggingface-hub>=0.24.2",
    "tqdm>=4.66.4",
    "numpy>=1.26.4",
    "dacite>=1.8.1",
    "seaborn>=0.13.2"
]

[project.optional-dependencies]
eval = [
    "lm-eval[vllm]==0.4.3"
]

# Enables the usage of setuptools_scm
[tool.setuptools_scm]

[tool.mypy]
check_untyped_defs = true
files = ["tests", "src/rbeval"]
